# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: limits_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_DSN=postgres://user:pass@db:5432/limits_db?sslmode=disable
      - CONFIG_PATH=/app/config/config.yml
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro

volumes:
  pgdata:
